Feature/authentication
CollegeSchedule/cs-android pull request #6
Opened 2020-11-03 09:28 UTC by Banjeq

done

2020-11-03 13:48 UTC, WhyWeLive requested changes

2020-11-03 13:48 UTC, WhyWeLive commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Для чего используется legacy библиотека?

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +
Зачем пустая строка?

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/res/layout-v21/authentication_fragment.xml
> +        android:textColor="#232323"
Файл colors

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/res/layout-v21/authentication_fragment.xml
> +    android:background="#E5E5E5">
Файл colors

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/res/drawable/sign_buttons.xml
> +            android:fillColor="#FF3B30"
Файл colors

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/SignUpErrorFragment.kt
> +                "task_to_scan",
Не нужно хардкодить, создай константу

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/SignUpErrorFragment.kt
> +        binding.signBottomButton.setOnClickListener {
this.binding...

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/SignUpErrorFragment.kt
> +        binding.signBottomButton.setOnClickListener {
this.requireActivity, this!!!

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/CodeScannerFragment.kt
> +class CodeScannerFragment : Fragment() {
Очень плохо, где наш способ работы с фрагментами? Где DataBinding?

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/CodeScannerFragment.kt
> +    private lateinit var codeScanner: CodeScanner
К переменам класса всегда обращайся через this

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +    }
Пустую линию между функциями

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +        requireActivity().intent.removeExtra(key)
```suggestion
        this.requireActivity().intent.removeExtra(key)
```

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +            .navigate(actionId, bundle)
Функция ради вызова другой функции не самая крутая вещь.

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +            1888 -> {
Хардкод плохая вещь, лучше в константу.

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                        "Need permission to scan qr code",
Локализация

2020-11-03 13:48 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                1888
Константа

2020-11-03 14:53 UTC, Banjeq commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/SignUpErrorFragment.kt
> +                "task_to_scan",
Где именно?

2020-11-03 14:58 UTC, Banjeq commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/SignUpErrorFragment.kt
> +                "task_to_scan",
Наверное 33-34 строки

2020-11-03 16:10 UTC, WhyWeLive requested changes

2020-11-03 16:10 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/SignUpErrorFragment.kt
> +        this.binding.profileString.text = profileError
```suggestion
        super.onViewCreated(view, savedInstanceState)
        
        val profileError: String = getString(R.string.auth_scanErrorAccNFString)
        
        this.binding.profileString.text = profileError
```

2020-11-03 16:10 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/SignUpErrorFragment.kt
> +            this.requireActivity().onBackPressed()
```suggestion
        }
        
        this.binding.signBottomButton.setOnClickListener {
            this.requireActivity().onBackPressed()
```

2020-11-03 16:10 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/CodeScannerFragment.kt
> +        }
```suggestion
        val activity = this.requireActivity()
        
        this.codeScanner = CodeScanner(activity, this.binding.scannerView)
        
        this.codeScanner.decodeCallback = DecodeCallback {
            activity.runOnUiThread {
                activity.intent
                    .putExtra("scan_result", it.text)
                Toast.makeText(activity, it.text, Toast.LENGTH_LONG).show()
                activity.onBackPressed()
            }
        }
        
        this.binding.scannerView.setOnClickListener {
            this.codeScanner.startPreview()
        }
```

2020-11-03 16:10 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                .setListener(null)
```suggestion
        val animDuration = 1000.toLong()
        
        this.binding.profileImage.apply {
            this.alpha = 0f
            this.visibility = View.VISIBLE

            this.animate()
                .alpha(1f)
                .setDuration(animDuration)
                .setListener(null)
        }

        this.binding.profileString.apply {
            this.alpha = 0f
            this.visibility = View.VISIBLE

            this.animate()
                .alpha(1f)
                .setDuration(animDuration)
                .setListener(null)
        }

        this.binding.formGroup.apply {
            val params = binding.formGroup.layoutParams as
                ConstraintLayout.LayoutParams

            val px = resources.displayMetrics.scaledDensity

            params.topToBottom = ConstraintLayout.LayoutParams.UNSET
            params.setMargins(
                20 * px.toInt(), 0, 20 * px.toInt(),
                20 * px.toInt()
            )

            params.bottomToTop = binding.signMainButton.id

            this.animate()
                .alpha(1f)
                .setDuration(animDuration)
                .setListener(null)
```

2020-11-04 16:28 UTC, WhyWeLive requested changes

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +
Да нахуя тут пустая линия?

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +            visibility = View.VISIBLE
```suggestion
            this.alpha = 0f
            this.visibility = View.VISIBLE
```

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +            visibility = View.VISIBLE
```suggestion
            this.alpha = 0f
            this.visibility = View.VISIBLE
```

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                        requireView(),
```suggestion
                    this.navTo(
                        this.requireView(),
```

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +            requestPermissions(
```suggestion
            this.requestPermissions(
```

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                    navTo(view, R.id.action_authFragment_to_codeScannerFragment)
```suggestion
                if (this.setupPermissions(view)) {
                    this.navTo(view, R.id.action_authFragment_to_codeScannerFragment)
```

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                    navTo(
```suggestion
                if (this.setupPermissions(this.view)) {
                    navTo(
```

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                activity.intent.removeExtra("task_to_scan")
В константу

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                    view,
```suggestion
                this.navTo(
                    view,
```

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +            activity.intent.removeExtra("scan_result")
В константу

2020-11-04 16:28 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                    "error_string",
В константу

2020-11-05 02:56 UTC, Banjeq commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                .getStringExtra("task_to_scan") == "true"
Константа ведь вне класса, а как там получить activity?

2020-11-05 02:56 UTC, Banjeq commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +            visibility = View.VISIBLE
А тут this зачем, это блин apply функция, даже IDE пишет что тут только один контекст

2020-11-05 02:56 UTC, Banjeq commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                activity.intent.removeExtra("task_to_scan")
Константа ведь вне класса, а как там получить activity?

2020-11-05 02:56 UTC, Banjeq commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +            activity.intent.removeExtra("scan_result")
Константа ведь вне класса, а как там получить activity?

2020-11-05 02:57 UTC, Banjeq commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                    "error_string",
Константа ведь вне класса, а как там получить activity?

2020-11-05 04:08 UTC, WhyWeLive requested changes

2020-11-05 04:08 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +const val authStringError = "error_string"
```suggestion
const val CAMERA_REQUEST_CODE = 1888
const val AUTH_SCAN_RESULT_CODE = "scan_result"
const val AUTH_SCAN_TASK_CODE = "task_to_scan"
const val AUTH_ERROR_CODE = "error_string"
```

Также, не забудь исправить использование эти констант в коде.

2020-11-05 04:08 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                this.respAnimation()
Что это за функция? Допиши полное название. Слова **resp** нет.

2020-11-05 04:08 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +                    this.hint = getString(R.string.auth_dummyEmail)
```suggestion
                    this.hint = this@AuthenticationFragment.getString(R.string.auth_dummyEmail)
```

2020-11-05 04:08 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/SignUpErrorFragment.kt
> +                "true"
Там разве нельзя boolean сразу указать?

2020-11-05 09:45 UTC, WhyWeLive approved these changes
LGTM

2020-11-05 09:45 UTC, WhyWeLive commented
Сделал хорошо, но это еще не вся работа, сейчас проверю на эмуляторе.

2020-11-05 12:02 UTC, WhyWeLive commented
- [ ] Используя стандартные шрифты Android для всех компонентов, если я не указывал иной в макете.
- [ ] На экране авторизации есть текст "Doesn't have an Account? Sign Up", переход на фрагмент скана кода должен срабатывать по нажатию на весь текст, а не только на "Sign Up"
- [ ] На всех экранах необходимо убрать ToolBar, а цвет статусбара сделать таким же, как у заднего фона

2020-11-05 12:04 UTC, WhyWeLive requested changes

2020-11-05 12:04 UTC, WhyWeLive commented on app/src/main/java/ru/nke/collegeschedule/schedule/ui/authentication/AuthenticationFragment.kt
> +    }
Функция ради вызова другой функции - плохая практика. Удали ее.

2020-11-06 06:22 UTC, Banjeq commented
> commit: 8368a4980db265c88328e24db915bb1fb319380a

![image](https://user-images.githubusercontent.com/38377394/98333303-025cf700-2033-11eb-8d97-0cd2cd138367.png)

2020-11-06 09:00 UTC, WhyWeLive commented
> Api 22 не умеет менять цвет итемов в статус баре, по этому:
> 
> > commit: [8368a49](https://github.com/CollegeSchedule/cs-android/commit/8368a4980db265c88328e24db915bb1fb319380a)
> 
> ![image](https://user-images.githubusercontent.com/38377394/98333303-025cf700-2033-11eb-8d97-0cd2cd138367.png)

Это хорошо, есть возможность поменять цвет заднего фона у нижней навигации?

2020-11-06 09:02 UTC, WhyWeLive approved these changes
LGTM

2020-11-06 09:32 UTC, Banjeq commented
> > Api 22 не умеет менять цвет итемов в статус баре, по этому:
> > > commit: [8368a49](https://github.com/CollegeSchedule/cs-android/commit/8368a4980db265c88328e24db915bb1fb319380a)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/38377394/98333303-025cf700-2033-11eb-8d97-0cd2cd138367.png)
> 
> Это хорошо, есть возможность поменять цвет заднего фона у нижней навигации?

Да, на Api 27+

2020-11-06 10:34 UTC, Banjeq commented
> commit: 8368a49

Это решение не работает на Huawei Api 29

2020-11-07 07:30 UTC, WhyWeLive submitted a review, later dismissed

2020-12-23 18:20 UTC, WhyWeLive submitted a review, later dismissed

2021-01-27 14:11 UTC, merged